# Site settings
# in the templates available like {{ site.myvariable }}.
title: Megan Davies Original Art
email: megan@mdavies.art
brand: Megan Davies
headline: Original Artwork from Megan Davies
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mdavies.art" # the base hostname & protocol for your site
copyright: All images and material on this site are copyright to Megan Davies 2008-2016. Do not reproduce without written permission. Images may vary depending on monitor settings.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: megan@mdavies.art

# Tracking
googleAnalitycsID: UA-83933844-1

