# Site settings
# in the templates available like {{ site.myvariable }}.
title: Original Art
email: megan@mdavies.art
brand: MDavies
headline: Original Artwork from Megan Davies
description: > # this means to ignore newlines until "baseurl:"
  MDavies Art
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mdavies.art" # the base hostname & protocol for your site
copyright: All images and material on this site are copyright of Megan Davies. Content herein should not be reproduced or redistributed without prior written consent.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 866507

# Tracking
googleAnalitycsID: UA-176265237-1

